[package]
name = "rinha_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = { version = "0.4.41", features = ["serde"] }
http-body-util = "0.1.3"
hyper = { version = "1.6.0", features = ["client"] }
hyper-util = "0.1.15"
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["rt-multi-thread"] }
tokio-postgres = "0.7.13"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
