[package]
name = "rinha"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"

clap = { version = "4.5.41", features = ["derive"] }

axum = "0.8.4"
axum-extra = { version = "0.10.1", features = ["query"] }

chrono = { version = "0.4.41", features = ["serde"] }

r2d2 = "0.8.10"
r2d2_sqlite = "0.31.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }

reqwest = { version = "0.12.22", default-features = false, features = ["json"] }

serde = { version = "1.0.219", features = ["derive"] }

tokio = { version = "1.47.0", features = ["rt-multi-thread", "signal"] }
futures = "0.3.31"

tarpc = { version = "0.36", features = ["tokio1", "tcp", "serde-transport-bincode"] }

tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
