services:
  api_0: &api
    image: localhost/rinha
    volumes:
      - sqlite:/data
    command: ["-m", "api", "-w", "worker:80"]
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

  api_1:
    <<: *api

  worker:
    image: localhost/rinha
    networks:
      - payment-processor
    volumes:
      - sqlite:/data
    command: ["-m", "worker"]
    depends_on:
      - grafana
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "140MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_0
      - api_1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  loki:
    image: grafana/loki:latest
    volumes:
      - loki:/loki

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - loki
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false

volumes:
  sqlite:
  loki:
  grafana:

networks:
  payment-processor:
    external: true
