services:
  api_0: &api
    image: localhost/rinha
    volumes:
      - sqlite:/data
    command:
      [
        "-m",
        "api",
        "-w",
        "worker:80",
        "-a",
        "YWRtaW5AYWRtaW4uY29tOmpMQUQ5NEJ1dml6VENUY0c=",
      ]
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "80MB"

  api_1:
    <<: *api

  worker:
    image: localhost/rinha
    networks:
      - payment-processor
    volumes:
      - sqlite:/data
    command:
      ["-m", "worker", "-a", "YWRtaW5AYWRtaW4uY29tOmpMQUQ5NEJ1dml6VENUY0c="]
    depends_on:
      - openobserve
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "140MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_0
      - api_1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "admin@admin.com"
      ZO_ROOT_USER_PASSWORD: "admin"
    ports:
      - "5080:5080"
    volumes:
      - openobserve:/data

volumes:
  sqlite:
  openobserve:

networks:
  payment-processor:
    external: true
