x-api_template: &api
  image: localhost/rinha
  volumes:
    - uds:/var/run
  command: ["-m", "api"]
  depends_on:
    - worker
  deploy:
    resources:
      limits:
        cpus: "0.4"
        memory: "80MB"

services:
  lb:
    image: localhost/rinha
    command: ["-m", "lb"]
    ports:
      - "9999:9999"
    volumes:
      - uds:/var/run
    depends_on:
      - api_0
      - api_1
    environment:
      API_N: "2"
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "80MB"

  api_0:
    <<: *api
    environment:
      API_N: "0"
      RUST_LOG: "info"

  api_1:
    <<: *api
    environment:
      API_N: "1"
      RUST_LOG: "info"

  worker:
    image: localhost/rinha
    command: ["-m", "worker"]
    networks:
      - payment-processor
    volumes:
      - uds:/var/run
    environment:
      SOCKET: "/var/run/worker.socket"
      RUST_LOG: "info"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "110MB"

volumes:
  uds:

networks:
  payment-processor:
    external: true
