services:
  api_0:
    build:
      context: https://github.com/Lothyriel/rinha_2025.git
    networks:
      - backend
    volumes:
      - sqlite_data:/sqlite
    command: ["api"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

  api_1:
    build:
      context: https://github.com/Lothyriel/rinha_2025.git
    networks:
      - backend
    volumes:
      - sqlite_data:/sqlite
    command: ["api"]
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

  worker:
    build:
      context: https://github.com/Lothyriel/rinha_2025.git
    networks:
      - backend
      - payment-processor
    volumes:
      - sqlite_data:/sqlite
    command: ["worker"]
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "240MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

volumes:
  sqlite_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
