services:
  api_0: &api
    image: localhost/rinha
    volumes:
      - uds:/socket
    command: ["-m", "api"]
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  api_1:
    <<: *api

  worker:
    image: localhost/rinha
    networks:
      - payment-processor
    volumes:
      - uds:/socket
    command: ["-m", "worker"]
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "260MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_0
      - api_1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

volumes:
  uds:

networks:
  payment-processor:
    external: true
