services:
  api_0:
    build:
      context: .
    networks:
      - backend
    volumes:
      - sqlite_data:/sqlite
    command: ["-m", "api", "-w", "worker:80"]
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

  api_1:
    build:
      context: .
    networks:
      - backend
    volumes:
      - sqlite_data:/sqlite
    command: ["-m", "api", "-w", "worker:80"]
    depends_on:
      - worker
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"
  worker:
    build:
      context: .
    networks:
      - backend
      - payment-processor
    volumes:
      - sqlite_data:/sqlite
    command: ["-m", "worker"]
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "240MB"

  nginx:
    image: nginx:latest
    ports:
      - "9999:80"
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api_0
      - api_1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

volumes:
  sqlite_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
